[platformio]
default_envs = simplebgc32_regular, storm32_stm32f1

[common]
platform = ststm32
framework = arduino
build_flags = !echo "-Wl,-u_printf_float -g -DCOMMIT_ID_SHORT=`git log --pretty=format:'%%h' -n 1` -DCOMMIT_ID_LONG=`git log --pretty=format:'%%H' -n 1`"
upload_protocol = serial
upload_flags = -m8n1
monitor_speed = 115200
lib_deps =
    askuric/Simple FOC@^2.3.5
    FlexWire
# Workaround for attribute((weak)) not working in SimpleFOC
lib_archive = false

[env:simplebgc32_regular]
extends = common
board = simplebgc32_regular

[env:storm32_stm32f1]
extends = common
board = storm32_stm32f1
build_flags = ${common.build_flags} -DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
