# vim: set ts=4 sw=4 sts=4 et :
gdb.execute("set logging overwrite on")
gdb.execute("set logging redirect on")
gdb.execute("set logging file utils/param_defs.py")
gdb.execute("set logging enabled on")

print('# Autogenerated from src/param-defs.c.inc')
print('from utils.param_map import *')
print('params = {')
params = {}

for param in param_map:
    # TODO: use gdb.parse_and_eval(), lookup_type()
    _id = int(gdb.execute(f'print (int) {param.enum_id}', to_string=True).split('=')[1].strip())
    if ParamFlag.const in param.flags:
        size = 4
        typ = 'uint32_t'
    else:
        # Print size as known to gdb, avoid complex lookup in the params array
        size = int(gdb.execute(f'print sizeof({param.name})', to_string=True).split('=')[1].strip())
        typ = gdb.execute(f'ptype {param.name}', to_string=True).split('=')[1].strip()
    name = param.name.lower()
    params[_id] = ParamDef(_id, name, size, typ, int(param.flags))
    print(f' {_id}: ParamDef({_id}, \'{name}\', {size}, \'{typ}\', ParamFlag({param.flags})),')

print('}')
#print('params = ', params)
typ = gdb.execute('quit')
