/* vim: set ts=4 sw=4 sts=4 et : */
#ifndef SERIAL_API_H
#define SERIAL_API_H

#include <stdint.h>

/* Copied verbatim from SimpleBGC_2_6_Serial_Protocol_Specification.pdf */
#define CMD_READ_PARAMS 82
#define CMD_WRITE_PARAMS 87
#define CMD_REALTIME_DATA 68
#define CMD_BOARD_INFO 86
#define CMD_CALIB_ACC 65
#define CMD_CALIB_GYRO 103
#define CMD_CALIB_EXT_GAIN 71
#define CMD_USE_DEFAULTS 70
#define CMD_CALIB_POLES 80
#define CMD_RESET 114
#define CMD_HELPER_DATA 72
#define CMD_CALIB_OFFSET 79
#define CMD_CALIB_BAT 66
#define CMD_MOTORS_ON 77
#define CMD_MOTORS_OFF 109
#define CMD_CONTROL 67
#define CMD_TRIGGER_PIN 84
#define CMD_EXECUTE_MENU 69
#define CMD_GET_ANGLES 73
#define CMD_CONFIRM 67
#define CMD_BOARD_INFO_3 20
#define CMD_READ_PARAMS_3 21
#define CMD_WRITE_PARAMS_3 22
#define CMD_REALTIME_DATA_3 23
#define CMD_REALTIME_DATA_4 25
#define CMD_SELECT_IMU_3 24
#define CMD_READ_PROFILE_NAMES 28
#define CMD_WRITE_PROFILE_NAMES 29
#define CMD_QUEUE_PARAMS_INFO_3 30
#define CMD_SET_ADJ_VARS_VAL 31
#define CMD_SAVE_PARAMS_3 32
#define CMD_READ_PARAMS_EXT 33
#define CMD_WRITE_PARAMS_EXT 34
#define CMD_AUTO_PID 35
#define CMD_SERVO_OUT 36
#define CMD_BODE_TEST_START_STOP 37
#define CMD_I2C_WRITE_REG_BUF 39
#define CMD_I2C_READ_REG_BUF 40
#define CMD_WRITE_EXTERNAL_DATA 41
#define CMD_READ_EXTERNAL_DATA 42
#define CMD_READ_ADJ_VARS_CFG 43
#define CMD_WRITE_ADJ_VARS_CFG 44
#define CMD_API_VIRT_CH_CONTROL 45
#define CMD_ADJ_VARS_STATE 46
#define CMD_EEPROM_WRITE 47
#define CMD_EEPROM_READ 48
#define CMD_CALIB_INFO 49
#define CMD_SIGN_MESSAGE 50
#define CMD_BOOT_MODE_3 51
#define CMD_SYSTEM_STATE 52
#define CMD_READ_FILE 53
#define CMD_WRITE_FILE 54
#define CMD_FS_CLEAR_ALL 55
#define CMD_AHRS_HELPER 56
#define CMD_RUN_SCRIPT 57
#define CMD_SCRIPT_DEBUG 58
#define CMD_CALIB_MAG 59
#define CMD_GET_ANGLES_EXT 61
#define CMD_READ_PARAMS_EXT2 62
#define CMD_WRITE_PARAMS_EXT2 63
#define CMD_GET_ADJ_VARS_VAL 64
#define CMD_CALIB_MOTOR_MAG_LINK 74
#define CMD_GYRO_CORRECTION 75
#define CMD_MODULE_LIST 76
#define CMD_DATA_STREAM_INTERVAL 85
#define CMD_REALTIME_DATA_CUSTOM 88
#define CMD_BEEP_SOUND 89
#define CMD_ENCODERS_CALIB_OFFSET_4 26
#define CMD_ENCODERS_CALIB_FLD_OFFSET_4 27
#define CMD_CONTROL_CONFIG 90
#define CMD_CALIB_ORIENT_CORR 91
#define CMD_COGGING_CALIB_INFO 92
#define CMD_CALIB_COGGING 93
#define CMD_CALIB_ACC_EXT_REF 94
#define CMD_PROFILE_SET 95
#define CMD_CAN_DEVICE_SCAN 96
#define CMD_CAN_DRV_HARD_PARAMS 97
#define CMD_CAN_DRV_STATE 98
#define CMD_CAN_DRV_CALIBRATE 99
#define CMD_READ_RC_INPUTS 100
#define CMD_REALTIME_DATA_CAN_DRV 101
#define CMD_EVENT 102
#define CMD_READ_PARAMS_EXT3 104
#define CMD_WRITE_PARAMS_EXT3 105
#define CMD_EXT_IMU_DEBUG_INFO 106
#define CMD_SET_DEVICE_ADDR 107
#define CMD_AUTO_PID2 108
#define CMD_EXT_IMU_CMD 110
#define CMD_READ_STATE_VARS 111
#define CMD_WRITE_STATE_VARS 112
#define CMD_SERIAL_PROXY 113
#define CMD_IMU_ADVANCED_CALIB 115
#define CMD_API_VIRT_CH_HIGH_RES 116
#define CMD_CALIB_ENCODER_LUT 117
#define CMD_CALIB_ENCODER_LUT_RES 118
#define CMD_WRITE_PARAMS_SET 119
#define CMD_CALIB_CUR_SENS 120
#define CMD_CONTROL_EXT 121
#define CMD_ENC_INT_CALIB 122
#define CMD_SYNC_MOTORS 123
#define CMD_EXT_LICENSE_INFO 124
#define CMD_VIBRATION_TEST_START_STOP 125
#define CMD_VIBRATION_TEST_DATA 126
#define CMD_CAN_DRV_TELEMETRY 127
#define CMD_EXT_MOTORS_ACTION 128
#define CMD_EXT_MOTORS_CONTROL 129
#define CMD_EXT_MOTORS_CONTROL_CONFIG 130
#define CMD_EXT_MOTORS_STATE 131
#define CMD_ADJ_VARS_INFO 132
#define CMD_CONTROL_QUAT 140
#define CMD_CONTROL_QUAT_STATUS 141
#define CMD_CONTROL_QUAT_CONFIG 142

#define CMD_EXT_SENS_CMD 150
#define CMD_TRANSPARENT_SAPI 151

#define CMD_SET_DEBUG_PORT 249
#define CMD_MAVLINK_INFO 250
#define CMD_MAVLINK_DEBUG 251
#define CMD_DEBUG_VARS_INFO_3 253
#define CMD_DEBUG_VARS_3 254
#define CMD_ERROR 255

enum serial_api_error_code_e {
    /* The most often used codes are: */
    ERR_CMD_SIZE = 1,
    ERR_WRONG_PARAMS = 2,
    ERR_CRYPTO = 4,
    ERR_UNKNOWN_COMMAND = 6,
    ERR_WRONG_STATE = 8,
    ERR_NOT_SUPPORTED = 9,
    ERR_OPERATION_FAILED = 10,
    ERR_TEMPORARY = 11,
    /* Codes related to file operations: */
    ERR_EEPROM_FAULT = 1,
    ERR_FILE_NOT_FOUND = 2,
    ERR_FAT = 3,
    ERR_NO_FREE_SPACE = 4,
    ERR_FAT_IS_FULL = 5,
    ERR_FILE_SIZE = 6,
    ERR_CRC = 7,
    ERR_LIMIT_REACHED = 8,
    ERR_FILE_CORRUPTED = 9,
    ERR_FS_WRONG_PARAMS = 10,
};

struct serial_api_control_req_s {
    uint8_t control_mode[3];
    struct {
        int16_t speed;
        int16_t angle;
    } value[3];
} __attribute__((packed));

enum serial_api_menu_cmd_id_e {
    MENU_CMD_NO = 0,
    MENU_CMD_PROFILE1 = 1,
    MENU_CMD_PROFILE2 = 2,
    MENU_CMD_PROFILE3 = 3,
    MENU_CMD_SWAP_PITCH_ROLL = 4,
    MENU_CMD_SWAP_YAW_ROLL = 5,
    MENU_CMD_CALIB_ACC = 6,
    MENU_CMD_RESET = 7,
    MENU_CMD_SET_ANGLE = 8,
    MENU_CMD_CALIB_GYRO = 9,
    MENU_CMD_MOTOR_TOGGLE = 10,
    MENU_CMD_MOTOR_ON = 11,
    MENU_CMD_MOTOR_OFF = 12,
    MENU_CMD_FRAME_UPSIDE_DOWN = 13,
    MENU_CMD_PROFILE4 = 14,
    MENU_CMD_PROFILE5 = 15,
    MENU_CMD_AUTO_PID = 16,
    MENU_CMD_LOOK_DOWN = 17,
    MENU_CMD_HOME_POSITION = 18,
    MENU_CMD_RC_BIND = 19,
    MENU_CMD_CALIB_GYRO_TEMP = 20,
    MENU_CMD_CALIB_ACC_TEMP = 21,
    MENU_CMD_BUTTON_PRESS = 22,
    MENU_CMD_RUN_SCRIPT1 = 23,
    MENU_CMD_RUN_SCRIPT2 = 24,
    MENU_CMD_RUN_SCRIPT3 = 25,
    MENU_CMD_RUN_SCRIPT4 = 26,
    MENU_CMD_RUN_SCRIPT5 = 27,
    MENU_CMD_CALIB_MAG = 33,
    MENU_CMD_LEVEL_ROLL_PITCH = 34,
    MENU_CMD_CENTER_YAW = 35,
    MENU_CMD_UNTWIST_CABLES = 36,
    MENU_CMD_SET_ANGLE_NO_SAVE = 37,
    MENU_HOME_POSITION_SHORTEST = 38,
    MENU_CENTER_YAW_SHORTEST = 39,
    MENU_ROTATE_YAW_180 = 40,
    MENU_ROTATE_YAW_180_FRAME_REL = 41,
    MENU_SWITCH_YAW_180_FRAME_REL = 42,
    MENU_SWITCH_POS_ROLL_90 = 43,
    MENU_START_TIMELAPSE = 44,
    MENU_CALIB_MOMENTUM = 45,
    MENU_LEVEL_ROLL = 46,
    MENU_REPEAT_TIMELAPSE = 47,
    MENU_LOAD_PROFILE_SET1 = 48,
    MENU_LOAD_PROFILE_SET2 = 49,
    MENU_LOAD_PROFILE_SET3 = 50,
    MENU_LOAD_PROFILE_SET4 = 51,
    MENU_LOAD_PROFILE_SET5 = 52,
    MENU_LOAD_PROFILE_SET_BACKUP = 53,
    MENU_INVERT_RC_ROLL = 54,
    MENU_INVERT_RC_PITCH = 55,
    MENU_INVERT_RC_YAW = 56,
    MENU_SNAP_TO_FIXED_POSITION = 57,
    MENU_CAMERA_REC_PHOTO_EVENT = 58,
    MENU_CAMERA_PHOTO_EVENT = 59,
    MENU_MOTORS_SAFE_STOP = 60,
    MENU_CALIB_ACC_AUTO = 61,
    MENU_RESET_IMU = 62,
    MENU_FORCED_FOLLOW_TOGGLE = 63,
    MENU_AUTO_PID_GAIN_ONLY = 64,
    MENU_LEVEL_PITCH = 65,
    MENU_MOTORS_SAFE_TOGGLE = 66,
    MENU_TIMELAPSE_STEP1 = 67,
    MENU_EXT_GYRO_ONLINE_CALIB = 68,
    MENU_DISABLE_FOLLOW_TOGGLE = 69,
    MENU_SET_CUR_POS_AS_HOME = 70,
    MENU_STOP_SCRIPT = 71,
    MENU_TRIPOD_MODE_OFF = 72,
    MENU_TRIPOD_MODE_ON = 73,
    MENU_SET_RC_TRIM = 74,
    MENU_HOME_POSITION_MOTORS = 75,
    MENU_RETRACTED_POSITION = 76,
    MENU_SHAKE_GENERATOR_OFF = 77,
    MENU_SHAKE_GENERATOR_ON = 78,
};

/* The only purpose of this for now is printing full messages for debug */
struct serial_api_port_state_s {
    uint8_t rx_buf[280];
    uint16_t rx_len;
    uint16_t rx_full_msg_len;
    uint8_t last_version;
    uint16_t rx_error_cnt;

    void (*cmd_rx_cb)(uint8_t cmd, const uint8_t *payload, uint8_t payload_len);
    void (*bytes_tx_cb)(const uint8_t *data, uint16_t len);
};

void serial_api_reset(struct serial_api_port_state_s *port);
void serial_api_rx_byte(struct serial_api_port_state_s *port, uint8_t byte);
void serial_api_tx_cmd(struct serial_api_port_state_s *port, uint8_t cmd,
        const uint8_t *payload, uint8_t payload_len);

#endif /* SERIAL_API_H */
